name: Atualizar Releases Automaticamente

on:
  push:
    branches:
      - main
    paths:
      - '*.apk'

jobs:
  atualizar-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      # ESTA ETAPA SÓ RODA SE A MENSAGEM TIVER "app tv"
      - name: Atualizar Release TV
        if: contains(github.event.head_commit.message, 'app tv')
        run: |
          if [ -f sccp1910-tv.apk ]; then
            MSG="${{ github.event.head_commit.message }}"
            VERSAO="${MSG##* }"
            gh release upload sccp1910tv sccp1910-tv.apk --clobber
            gh release edit sccp1910tv --title "Versão TV $VERSAO" --notes "$MSG"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ESTA ETAPA SÓ RODA SE A MENSAGEM TIVER "app mobile"
      - name: Atualizar Release Mobile
        if: contains(github.event.head_commit.message, 'app mobile')
        run: |
          if [ -f sccp1910-mobile.apk ]; then
            MSG="${{ github.event.head_commit.message }}"
            VERSAO="${MSG##* }"
            gh release upload sccp1910mobile sccp1910-mobile.apk --clobber
            gh release edit sccp1910mobile --title "Versão Mobile $VERSAO" --notes "$MSG"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
